name: Release

on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create WrathClassic Package
        uses: BigWigsMods/packager@v2
        with:
          args: -g wrath

      - name: Create BCClassic Package
        uses: BigWigsMods/packager@v2
        with:
          args: -g bcc

      - name: Create Classic Package
        uses: BigWigsMods/packager@v2
        with:
          args: -g classic

      - name: Create CataClassic Package
        uses: BigWigsMods/packager@v2
        with:
          args: -g cata